### ISSUE TITLE
tvhclient on AppleTV with HomePod as the audio out.

### ISSUE THREAD

**Issue by yhur** [zipleen/tvheadend-iphone-client#290]
Hi,

I like the tvhclient for Apple TV and like it.

The only problem is when I use this with the HomePod minis as the Audio out, the video and audio doesn't sync. Event time gap is randomly changing. 

Just for the debug data, when the Apple TV's audio is set to the plain television's speaker, the audio/video plays flawlessly.

Could this be fixed? Or is it just me having this problem.

**Comment by nick297** [comment]
I seem to have this issue too, have you had any success fixing it?

**Comment by rewulff** [comment]
Same here. No fix or workaround yet.
On live tv and recordings out of sync.
The HomePod uses eArc to transport audio. A delay is very normal (like bt highq codecs) normally the video player delays the video. Maybe vlc is capable but needs some settings.
Have anyone tried to stream videos by vlc while sound on HomePod?

**Comment by yhur** [comment]
I have the same problem with VLC as well.

**Comment by rewulff** [comment]
In this case we should try to get the get the vlc team to fix the issue. This should fix the issue in the TvhClient as well.

**Comment by CV8R** [comment]
Still an issue!

**Comment by masterchiefofbikeride** [comment]
Even though I know this issue will never be fixed as the maintainer of TVHclient seems to give a fuck anymore about his program ... I just wanted to say that this issue still exists and is annoying as fuck

**Comment by zipleen** [comment]
form the latest version of tvhclient for tvOS (1.4.1) this will not longer be an issue. 

tvhclient for iOS should not have any issues after 4.1.2 as well !

**Comment by masterchiefofbikeride** [comment]
Still only version 1.4.0. in the tvOS AppStore so still no fix
